import type { Stage2Question } from "./types";

/** §6.2 — ART bank (11), transcribed verbatim. */
export const ART_BANK: readonly Stage2Question[] = [
  {
    id: "art_1",
    field: "ART",
    prompt: "Ты делаешь то, что хочешь сам, или решаешь задачу заказчика красиво?",
    axes: ["R1"],
    groupA: ["ART_PERF", "ART_WRITE"],
    groupB: ["ART_GRAPH", "ART_UXVIS"],
  },
  {
    id: "art_2",
    field: "ART",
    prompt: "Твой результат существует во времени — его нельзя увидеть целиком за секунду.",
    axes: ["R2"],
    groupA: ["ART_FILM", "ART_ANIM", "ART_MUSIC"],
    groupB: ["ART_GRAPH", "ART_PHOTO"],
  },
  {
    id: "art_3",
    field: "ART",
    prompt: "Тридцать человек в команде, и всё зависит от согласованности. Или ты один за столом?",
    axes: ["R3"],
    groupA: ["ART_FILM", "ART_GAMED"],
    groupB: ["ART_WRITE", "ART_PHOTO"],
  },
  {
    id: "art_4",
    field: "ART",
    prompt: "Твоя форма ограничена тем, что её надо произвести на заводе.",
    axes: ["R1", "R4"],
    groupA: ["ART_IND"],
    groupB: ["ART_GRAPH"],
  },
  {
    id: "art_5",
    field: "ART",
    prompt: "Твой инструмент — собственное тело и присутствие перед людьми.",
    axes: ["R2"],
    groupA: ["ART_PERF"],
    groupB: "rest",
  },
  {
    id: "art_6",
    field: "ART",
    prompt: "Тебе интереснее, как это выглядит, или как это работает для человека?",
    axes: ["R1"],
    groupA: ["ART_UXVIS"],
    groupB: [],
  },
  {
    id: "art_7",
    field: "ART",
    prompt: "Проект идёт четыре года, и за него ты отвечаешь юридически.",
    axes: ["R1", "A_HORIZON"],
    groupA: ["ART_ARCH"],
    groupB: "rest",
  },
  {
    id: "art_8",
    field: "ART",
    prompt: "Ты работаешь с тем, что уже есть в мире, а не с чистым листом.",
    axes: ["R1"],
    groupA: ["ART_PHOTO", "ART_MEDIA"],
    groupB: ["ART_ANIM", "ART_WRITE"],
  },
  {
    id: "art_9",
    field: "ART",
    prompt: "Тебе важно, чтобы то, что ты сделал, было правдой, а не только красивым.",
    axes: ["R1"],
    groupA: ["ART_MEDIA"],
    groupB: "rest",
  },
  {
    id: "art_10",
    field: "ART",
    prompt: "Ты проектируешь не картинку, а правила, по которым другой человек будет играть.",
    axes: ["R1"],
    groupA: ["ART_GAMED"],
    groupB: ["ART_ANIM"],
  },
  {
    id: "art_11",
    field: "ART",
    prompt: "Работа привязана к сезону и к тому, что люди носят прямо сейчас.",
    axes: ["R2"],
    groupA: ["ART_FASH"],
    groupB: ["ART_GRAPH"],
  },
];
