import type { Stage2Question } from "./types";

/** §6.2 — BIZ bank (10), transcribed verbatim. */
export const BIZ_BANK: readonly Stage2Question[] = [
  {
    id: "biz_1",
    field: "BIZ",
    prompt: "Твой доход зависит от результата разговора, который ты ведёшь сегодня. Это драйв или ужас?",
    axes: ["B2", "B3"],
    groupA: ["BIZ_SALES", "BIZ_ENT"],
    groupB: ["BIZ_ACC", "BIZ_BANK"],
  },
  {
    id: "biz_2",
    field: "BIZ",
    prompt: "Что приятнее: найти ошибку в отчёте на миллион, или убедить человека дать миллион?",
    axes: ["B1", "B2"],
    groupA: ["BIZ_ACC", "BIZ_FIN"],
    groupB: ["BIZ_SALES", "BIZ_ENT"],
  },
  {
    id: "biz_3",
    field: "BIZ",
    prompt: "Тебе нравится, когда правила жёсткие и их надо знать наизусть?",
    axes: ["B5"],
    groupA: ["BIZ_ACC", "BIZ_TRADE", "BIZ_BANK"],
    groupB: ["BIZ_ENT", "BIZ_MKT"],
  },
  {
    id: "biz_4",
    field: "BIZ",
    prompt: "Ты отвечаешь за результат, но никто тебе не подчиняется. Как тебе такое?",
    axes: ["B2"],
    groupA: ["BIZ_MGMT"],
    groupB: ["BIZ_FIN"],
  },
  {
    id: "biz_5",
    field: "BIZ",
    prompt: "Управлять физическими вещами — складами, машинами, сроками — через таблицу.",
    axes: ["B1"],
    groupA: ["BIZ_SCM"],
    groupB: ["BIZ_MKT"],
  },
  {
    id: "biz_6",
    field: "BIZ",
    prompt: "Тебе интереснее, почему люди покупают, или сколько они покупают?",
    axes: ["B1"],
    groupA: ["BIZ_MKT"],
    groupB: ["BIZ_BA"],
  },
  {
    id: "biz_7",
    field: "BIZ",
    prompt: "Работа с людьми внутри компании: конфликты, наём, развитие.",
    axes: ["B2"],
    groupA: ["BIZ_HR"],
    groupB: ["BIZ_FIN"],
  },
  {
    id: "biz_8",
    field: "BIZ",
    prompt: "Готов два года работать без гарантии, что вообще что-то получится?",
    axes: ["B3"],
    groupA: ["BIZ_ENT"],
    groupB: "rest",
  },
  {
    id: "biz_9",
    field: "BIZ",
    prompt: "Объект сделки — здание или земля, цикл — три года.",
    axes: ["B4"],
    groupA: ["BIZ_RE"],
    groupB: ["BIZ_FIN"],
  },
  {
    id: "biz_10",
    field: "BIZ",
    prompt: "Тебе нравится разбираться, что данные говорят о бизнесе, но не принимать решение самому?",
    axes: ["B1"],
    groupA: ["BIZ_BA"],
    groupB: ["BIZ_MGMT"],
  },
];
