import type { Stage2Question } from "./types";

/** §6.2 — EDU bank (10), transcribed verbatim. */
export const EDU_BANK: readonly Stage2Question[] = [
  {
    id: "edu_1",
    field: "EDU",
    prompt: "Тридцать человек в комнате, и все должны тебя слушать. Или один человек и полтора часа разговора?",
    axes: ["D2"],
    groupA: ["EDU_TEACH"],
    groupB: ["EDU_PSY"],
  },
  {
    id: "edu_2",
    field: "EDU",
    prompt: "Прогресс подопечного за год — одно новое слово. Это победа или тоска?",
    axes: ["D2", "D3"],
    groupA: ["EDU_SPEC", "EDU_SLP"],
    groupB: ["EDU_TEACH"],
  },
  {
    id: "edu_3",
    field: "EDU",
    prompt: "Ты готов слушать тяжёлые вещи и не уносить их домой?",
    axes: ["D3"],
    groupA: ["EDU_CLIN", "EDU_SOC"],
    groupB: ["EDU_INSTR", "EDU_COACH"],
  },
  {
    id: "edu_4",
    field: "EDU",
    prompt: "Тебе интереснее сам человек или то, как устроено обучение?",
    axes: ["D4"],
    groupA: ["EDU_INSTR"],
    groupB: ["EDU_PSY"],
  },
  {
    id: "edu_5",
    field: "EDU",
    prompt: "Дети до шести лет: много движения, мало разговоров, всё через игру.",
    axes: ["D1"],
    groupA: ["EDU_EARLY"],
    groupB: ["EDU_HIGH"],
  },
  {
    id: "edu_6",
    field: "EDU",
    prompt: "Проблема твоего подопечного — не в голове, а в жизни: деньги, семья, документы.",
    axes: ["D3"],
    groupA: ["EDU_SOC"],
    groupB: ["EDU_PSY"],
  },
  {
    id: "edu_7",
    field: "EDU",
    prompt: "Ты работаешь со здоровым человеком, который просто не знает, чего хочет.",
    axes: ["D3"],
    groupA: ["EDU_COACH"],
    groupB: ["EDU_CLIN"],
  },
  {
    id: "edu_8",
    field: "EDU",
    prompt: "Тебе важно, чтобы рядом с преподаванием было собственное исследование.",
    axes: ["D4"],
    groupA: ["EDU_HIGH"],
    groupB: ["EDU_TEACH"],
  },
  {
    id: "edu_9",
    field: "EDU",
    prompt: "Подростки приходят добровольно и могут в любой момент уйти.",
    axes: ["D1"],
    groupA: ["EDU_YOUTH"],
    groupB: ["EDU_TEACH"],
  },
  {
    id: "edu_10",
    field: "EDU",
    prompt: "Твоя работа — поставить конкретный навык, и его можно измерить.",
    axes: ["D2"],
    groupA: ["EDU_SLP"],
    groupB: ["EDU_PSY"],
  },
];
