import type { Stage2Question } from "./types";

/** §6.2 — ENV bank (10), transcribed verbatim. */
export const ENV_BANK: readonly Stage2Question[] = [
  {
    id: "env_1",
    field: "ENV",
    prompt: "Твоя цель — сохранить то, что есть, или вырастить как можно больше?",
    axes: ["V3"],
    groupA: ["ENV_ECO", "ENV_FOREST"],
    groupB: ["ENV_AGRO", "ENV_ANIM"],
  },
  {
    id: "env_2",
    field: "ENV",
    prompt: "Погода может обнулить год работы. Готов?",
    axes: ["V4"],
    groupA: ["ENV_AGRO"],
    groupB: ["ENV_SUST", "ENV_CLIM"],
  },
  {
    id: "env_3",
    field: "ENV",
    prompt: "Сколько месяцев в году ты готов провести не в помещении?",
    axes: ["V2"],
    groupA: ["ENV_GEO", "ENV_AGRO"],
    groupB: ["ENV_CLIM", "ENV_SUST"],
  },
  {
    id: "env_4",
    field: "ENV",
    prompt: "Твой объект — живое животное в промышленном количестве.",
    axes: ["V1"],
    groupA: ["ENV_ANIM"],
    groupB: ["ENV_AGRO"],
  },
  {
    id: "env_5",
    field: "ENV",
    prompt: "Ты работаешь с данными и моделями о природе, а не с самой природой.",
    axes: ["V2"],
    groupA: ["ENV_CLIM"],
    groupB: ["ENV_ECO"],
  },
  {
    id: "env_6",
    field: "ENV",
    prompt: "Результат твоей работы увидят твои внуки.",
    axes: ["V4"],
    groupA: ["ENV_FOREST"],
    groupB: ["ENV_FOOD"],
  },
  {
    id: "env_7",
    field: "ENV",
    prompt: "Экспедиции, керн, карты, месторождение.",
    axes: ["V1", "V2"],
    groupA: ["ENV_GEO"],
    groupB: ["ENV_HYDRO"],
  },
  {
    id: "env_8",
    field: "ENV",
    prompt: "Вода: кому сколько достанется, и это политический вопрос.",
    axes: ["V1"],
    groupA: ["ENV_HYDRO"],
    groupB: ["ENV_ECO"],
  },
  {
    id: "env_9",
    field: "ENV",
    prompt: "Ты внутри компании объясняешь, почему нельзя делать так, как выгоднее.",
    axes: ["V3"],
    groupA: ["ENV_SUST"],
    groupB: ["ENV_ECO"],
  },
  {
    id: "env_10",
    field: "ENV",
    prompt: "Продукт, который люди съедят: вкус, срок хранения, безопасность.",
    axes: ["V1", "V3"],
    groupA: ["ENV_FOOD"],
    groupB: [],
  },
];
