import type { Stage2Question } from "./types";

/** §6.2 — LAW bank (10), transcribed verbatim. */
export const LAW_BANK: readonly Stage2Question[] = [
  {
    id: "law_1",
    field: "LAW",
    prompt: "В зале есть человек, который хочет, чтобы ты проиграл. Это заводит?",
    axes: ["L1"],
    groupA: ["LAW_CRIM"],
    groupB: ["LAW_CORP", "LAW_COMP"],
  },
  {
    id: "law_2",
    field: "LAW",
    prompt: "Тебе интереснее применять правила или менять их?",
    axes: ["L4"],
    groupA: ["LAW_GOV", "LAW_POL"],
    groupB: ["LAW_CORP", "LAW_JUD"],
  },
  {
    id: "law_3",
    field: "LAW",
    prompt: "Восемь часов с документом, каждое слово имеет цену. Норма?",
    axes: ["L2"],
    groupA: ["LAW_CORP", "LAW_TAX"],
    groupB: ["LAW_DIPL"],
  },
  {
    id: "law_4",
    field: "LAW",
    prompt: "Ты готов быть тем, кто говорит своей компании «так нельзя»?",
    axes: ["L4"],
    groupA: ["LAW_COMP"],
    groupB: ["LAW_CORP"],
  },
  {
    id: "law_5",
    field: "LAW",
    prompt: "Твой клиент — страна, а не человек и не фирма.",
    axes: ["L4"],
    groupA: ["LAW_INTL", "LAW_DIPL"],
    groupB: ["LAW_CRIM"],
  },
  {
    id: "law_6",
    field: "LAW",
    prompt: "Нужно свободно работать на двух-трёх языках. Это плюс или барьер?",
    axes: ["L4"],
    groupA: ["LAW_INTL", "LAW_DIPL"],
    groupB: ["LAW_TAX"],
  },
  {
    id: "law_7",
    field: "LAW",
    prompt: "Тебе важно оставаться беспристрастным, даже когда ты на чьей-то стороне внутренне?",
    axes: ["L1"],
    groupA: ["LAW_JUD"],
    groupB: ["LAW_CRIM"],
  },
  {
    id: "law_8",
    field: "LAW",
    prompt: "Ресурсов мало, зарплата ниже рынка, но ты делаешь то, во что веришь.",
    axes: ["A_RISK", "L4"],
    groupA: ["LAW_NGO"],
    groupB: ["LAW_CORP"],
  },
  {
    id: "law_9",
    field: "LAW",
    prompt: "Тебе интересно, как устроен город — транспорт, жильё, кто что решает?",
    axes: ["L4"],
    groupA: ["LAW_URB"],
    groupB: ["LAW_GOV"],
  },
  {
    id: "law_10",
    field: "LAW",
    prompt: "Ты хочешь понимать политику или участвовать в ней?",
    axes: ["L3"],
    groupA: ["LAW_POL"],
    groupB: ["LAW_DIPL", "LAW_GOV"],
  },
];
