import type { Stage2Question } from "./types";

/** §6.2 — MED bank (11), transcribed verbatim. */
export const MED_BANK: readonly Stage2Question[] = [
  {
    id: "med_1",
    field: "MED",
    prompt: "Операционная: руки внутри человека, результат виден за часы. Твоё?",
    axes: ["M1", "M2"],
    groupA: ["MED_SURG"],
    groupB: ["MED_GP", "MED_DIAG"],
  },
  {
    id: "med_2",
    field: "MED",
    prompt: "Тебе комфортнее видеть одного пациента годами или решать проблему и отпускать?",
    axes: ["M3"],
    groupA: ["MED_GP", "MED_REHAB"],
    groupB: ["MED_SURG", "MED_EMS"],
  },
  {
    id: "med_3",
    field: "MED",
    prompt: "Решение надо принять за две минуты при неполной информации, на улице, без коллег рядом.",
    axes: ["M2"],
    groupA: ["MED_EMS"],
    groupB: ["MED_DIAG", "MED_PHARM"],
  },
  {
    id: "med_4",
    field: "MED",
    prompt: "Работать с веществом, а не с телом — состав, дозировка, взаимодействие. Интересно?",
    axes: ["M1"],
    groupA: ["MED_PHARM"],
    groupB: "rest",
  },
  {
    id: "med_5",
    field: "MED",
    prompt: "Ты готов, чтобы твой рабочий инструмент был разговор, а не процедура?",
    axes: ["M1"],
    groupA: ["MED_PSY"],
    groupB: ["MED_SURG", "MED_DENT"],
  },
  {
    id: "med_6",
    field: "MED",
    prompt: "Смотреть на снимок и находить то, что другие не увидели, почти не встречаясь с пациентом.",
    axes: ["M1", "M3"],
    groupA: ["MED_DIAG"],
    groupB: ["MED_NURS"],
  },
  {
    id: "med_7",
    field: "MED",
    prompt: "Тонкая работа в поле размером с ладонь, каждый день, много лет.",
    axes: ["M1"],
    groupA: ["MED_DENT"],
    groupB: ["MED_GP"],
  },
  {
    id: "med_8",
    field: "MED",
    prompt: "Пациент не может сказать, что болит. Это интересная задача или безнадёжная?",
    axes: ["M1"],
    groupA: ["MED_VET"],
    groupB: "rest",
  },
  {
    id: "med_9",
    field: "MED",
    prompt: "Тебе важнее вылечить одного или сделать так, чтобы тысячи не заболели?",
    axes: ["M4"],
    groupA: ["MED_PUB"],
    groupB: "rest",
  },
  {
    id: "med_10",
    field: "MED",
    prompt: "Прогресс идёт месяцами и измеряется сантиметрами движения. Хватит терпения?",
    axes: ["M2", "M3"],
    groupA: ["MED_REHAB"],
    groupB: ["MED_SURG"],
  },
  {
    id: "med_11",
    field: "MED",
    prompt: "Ты готов к тому, что рядом с пациентом ты проводишь больше часов, чем врач, а решение принимает он?",
    axes: ["M1", "A_INFL"],
    groupA: ["MED_NURS"],
    groupB: ["MED_GP"],
  },
];
