import type { Stage2Question } from "./types";

/** §6.2 — SEC bank (10), transcribed verbatim. */
export const SEC_BANK: readonly Stage2Question[] = [
  {
    id: "sec_1",
    field: "SEC",
    prompt: "Устав определяет не только работу, но и как ты живёшь. Приемлемо?",
    axes: ["C3"],
    groupA: ["SEC_MIL"],
    groupB: ["SEC_SPSCI", "SEC_HSE"],
  },
  {
    id: "sec_2",
    field: "SEC",
    prompt: "Ты идёшь туда, откуда все убегают.",
    axes: ["C2"],
    groupA: ["SEC_FIRE"],
    groupB: ["SEC_FOREN", "SEC_HSE"],
  },
  {
    id: "sec_3",
    field: "SEC",
    prompt: "У тебя власть над другими людьми, и её можно применить неправильно. Как ты к этому?",
    axes: ["C4"],
    groupA: ["SEC_POL"],
    groupB: ["SEC_GUARD"],
  },
  {
    id: "sec_4",
    field: "SEC",
    prompt: "Лаборатория, следы, микроскоп — внутри расследования, но не на улице.",
    axes: ["C1", "C4"],
    groupA: ["SEC_FOREN"],
    groupB: ["SEC_POL"],
  },
  {
    id: "sec_5",
    field: "SEC",
    prompt: "Твоя работа — чтобы ничего не случилось, и за это тебя не похвалят.",
    axes: ["C4"],
    groupA: ["SEC_HSE"],
    groupB: ["SEC_FIRE"],
  },
  {
    id: "sec_6",
    field: "SEC",
    prompt: "Твоё тело — твой рабочий инструмент, и карьера закончится к тридцати пяти.",
    axes: ["C1"],
    groupA: ["SEC_ATHL"],
    groupB: ["SEC_COACH"],
  },
  {
    id: "sec_7",
    field: "SEC",
    prompt: "Ты развиваешь чужое тело и чужую волю, а не своё.",
    axes: ["C1", "C4"],
    groupA: ["SEC_COACH"],
    groupB: ["SEC_ATHL"],
  },
  {
    id: "sec_8",
    field: "SEC",
    prompt: "Тебе интереснее наука о том, как работает тело под нагрузкой.",
    axes: ["C1"],
    groupA: ["SEC_SPSCI"],
    groupB: ["SEC_COACH"],
  },
  {
    id: "sec_9",
    field: "SEC",
    prompt: "Ты планируешь на случай катастрофы, которая может не случиться никогда.",
    axes: ["C4"],
    groupA: ["SEC_EMERG"],
    groupB: ["SEC_FIRE"],
  },
  {
    id: "sec_10",
    field: "SEC",
    prompt: "Надёжность и присутствие важнее навыков; входной порог низкий.",
    axes: ["C1"],
    groupA: ["SEC_GUARD"],
    groupB: "rest",
  },
];
