import type { Stage2Question } from "./types";

/** §6.2 — TRD bank (10), transcribed verbatim. */
export const TRD_BANK: readonly Stage2Question[] = [
  {
    id: "trd_1",
    field: "TRD",
    prompt: "Ты хочешь видеть результат в конце дня или в конце года?",
    axes: ["A_HORIZON"],
    groupA: ["TRD_AUTO", "TRD_CULIN"],
    groupB: ["TRD_CONS"],
  },
  {
    id: "trd_2",
    field: "TRD",
    prompt: "Ты готов учиться три-четыре года и потратить большие деньги ради допуска к работе?",
    axes: ["T3"],
    groupA: ["TRD_PILOT", "TRD_AVTECH"],
    groupB: ["TRD_WELD", "TRD_AUTO"],
  },
  {
    id: "trd_3",
    field: "TRD",
    prompt: "Работа на себя — сам ищешь клиентов, сам отвечаешь. Или стабильная смена и зарплата?",
    axes: ["T4"],
    groupA: ["TRD_ELEC", "TRD_BEAUTY"],
    groupB: ["TRD_RAIL", "TRD_CNC"],
  },
  {
    id: "trd_4",
    field: "TRD",
    prompt: "Опасность, которую не видно: ток, давление, газ.",
    axes: ["T1"],
    groupA: ["TRD_ELEC", "TRD_HVAC"],
    groupB: ["TRD_CULIN"],
  },
  {
    id: "trd_5",
    field: "TRD",
    prompt: "Найти причину поломки — это как расследование. Нравится?",
    axes: ["T1"],
    groupA: ["TRD_AUTO"],
    groupB: ["TRD_WELD"],
  },
  {
    id: "trd_6",
    field: "TRD",
    prompt: "Точность в сотые доли миллиметра, программа, станок, тишина.",
    axes: ["T1", "T3"],
    groupA: ["TRD_CNC"],
    groupB: ["TRD_CONS"],
  },
  {
    id: "trd_7",
    field: "TRD",
    prompt: "Тебя не смущает, что рядом с тобой каждый день клиент, и надо с ним говорить.",
    axes: ["T1"],
    groupA: ["TRD_BEAUTY", "TRD_CULIN"],
    groupB: ["TRD_CNC", "TRD_WELD"],
  },
  {
    id: "trd_8",
    field: "TRD",
    prompt: "График по часам, смены, ночь, инструкция на каждый шаг.",
    axes: ["T3"],
    groupA: ["TRD_RAIL", "TRD_AVTECH"],
    groupB: ["TRD_AUTO"],
  },
  {
    id: "trd_9",
    field: "TRD",
    prompt: "Ты управляешь движением машин и грузов, но сам сидишь на месте.",
    axes: ["T1", "T2"],
    groupA: ["TRD_LOG"],
    groupB: ["TRD_RAIL"],
  },
  {
    id: "trd_10",
    field: "TRD",
    prompt: "Пятнадцать минут — и твою работу оценят вслух, при тебе.",
    axes: ["A_HORIZON"],
    groupA: ["TRD_CULIN"],
    groupB: ["TRD_CONS"],
  },
];
