/**
 * Hand-written shape of the tables and RPCs in `supabase/migrations/*.sql`.
 *
 * Not generated by `supabase gen types` because that needs a live project this
 * codebase does not have yet. Once a real project exists, running
 * `supabase gen types typescript --project-id <id> > lib/supabase/types.ts`
 * replaces this file with the authoritative version — keep the shapes below in
 * sync with the SQL until then.
 *
 * Every table/function shape below matches `GenericTable`/`GenericFunction`
 * from `@supabase/postgrest-js` exactly (down to the `Relationships: []`
 * field): the Supabase client's generic falls back to `never` for every
 * query result, silently, if this `Database` type doesn't structurally
 * satisfy that shape — there is no type error at the call site to point back
 * here, only "Property does not exist on type 'never'" wherever the client
 * is used.
 */
export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: string;
          role: "student" | "parent" | null;
          email: string;
          name: string;
          auth_provider: "email" | "google";
          onboarding_completed: boolean;
          created_at: string;
        };
        Insert: Record<string, never>;
        Update: Record<string, never>;
        Relationships: [];
      };
      parent_child_links: {
        Row: {
          parent_user_id: string;
          student_user_id: string;
          created_at: string;
          invite_code_used: string | null;
        };
        Insert: Record<string, never>;
        Update: Record<string, never>;
        Relationships: [];
      };
      student_state: {
        Row: {
          student_user_id: string;
          schema_version: number;
          state: unknown;
          updated_at: string;
        };
        Insert: {
          student_user_id: string;
          schema_version: number;
          state: unknown;
          updated_at?: string;
        };
        Update: Partial<{
          schema_version: number;
          state: unknown;
          updated_at: string;
        }>;
        Relationships: [];
      };
      parent_notes: {
        Row: {
          id: string;
          parent_user_id: string;
          student_user_id: string;
          target_type: "door" | "action" | "general";
          target_id: string | null;
          body: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          parent_user_id: string;
          student_user_id: string;
          target_type: "door" | "action" | "general";
          target_id?: string | null;
          body: string;
          created_at?: string;
        };
        Update: Record<string, never>;
        Relationships: [];
      };
      parent_career_signal: {
        Row: {
          parent_user_id: string;
          student_user_id: string;
          parent_direction: string | null;
          parent_priorities: string | null;
          parent_support: string | null;
          updated_at: string;
        };
        Insert: {
          parent_user_id: string;
          student_user_id: string;
          parent_direction?: string | null;
          parent_priorities?: string | null;
          parent_support?: string | null;
          updated_at?: string;
        };
        Update: {
          parent_direction?: string | null;
          parent_priorities?: string | null;
          parent_support?: string | null;
          updated_at?: string;
        };
        Relationships: [];
      };
    };
    Views: Record<string, never>;
    Functions: {
      create_parent_invite: {
        Args: Record<string, never>;
        Returns: { code: string; expires_at: string }[];
      };
      get_invite_info: {
        Args: { p_code: string };
        Returns: { valid: boolean; reason: string; student_name: string | null }[];
      };
      redeem_parent_invite: {
        Args: { p_code: string };
        Returns: { status: string }[];
      };
      revoke_parent_link: {
        Args: { p_parent_id: string };
        Returns: undefined;
      };
      rename_self: {
        Args: { p_name: string };
        Returns: undefined;
      };
      mark_onboarding_complete: {
        Args: Record<string, never>;
        Returns: undefined;
      };
    };
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
}
